
require('settings')
-- Plugins setting
require('plugins')
require('plugconfig.nvim-web-devicons')
require('plugconfig.OneDark')
require('plugconfig.lualine')
require('plugconfig.treesitter')
require('plugconfig.hop')
require('plugconfig.colorful-winsep')
require('plugconfig.comment')
require('plugconfig.hlchunk')
require('plugconfig.vim-markdown')
require('plugconfig.cmp-nvim-lsp')
require('plugconfig.nvim-cmp')
require('plugconfig.nvim-lspconfig')
-- Will error if use below. Different require in packger plugins.lua
-- require('plugconfig.dashboard')
require('plugconfig.nvim-tree')
require('plugconfig.mason')
require("nvim-surround").setup()
